# name: Convert Readme
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y pandoc
#           chmod +x ./convert.sh

#       - name: Run conversion script
#         run: ./convert.sh
